-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 10:27:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AirplaneTickets
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AirplaneTickets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AirplaneTickets` DEFAULT CHARACTER SET utf8 ;
USE `AirplaneTickets` ;

-- -----------------------------------------------------
-- Table `AirplaneTickets`.`airplane_models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`airplane_models` (
  `airplanes_models_id` INT NOT NULL,
  `airplanes_models_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`airplanes_models_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirplaneTickets`.`airplanes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`airplanes` (
  `airplane_id` INT NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `range_miles` INT NOT NULL,
  `seats_count` INT NOT NULL,
  `airplane_model_id` INT NOT NULL,
  `seat_class_id` INT NOT NULL,
  PRIMARY KEY (`airplane_id`, `airplane_model_id`, `seat_class_id`),
  INDEX `fk_airplanes_manufactors1_idx` (`airplane_model_id` ASC) VISIBLE,
  INDEX `fk_airplanes_seat_classes1_idx` (`seat_class_id` ASC) VISIBLE,
  CONSTRAINT `fk_airplanes_manufactors1`
    FOREIGN KEY (`airplane_model_id`)
    REFERENCES `AirplaneTickets`.`airplane_models` (`airplanes_models_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_airplanes_seat_classes1`
    FOREIGN KEY (`seat_class_id`)
    REFERENCES `AirplaneTickets`.`seat_classes` (`seat_class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirplaneTickets`.`airports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`airports` (
  `airport_id` INT NOT NULL,
  `airport_name` VARCHAR(45) NOT NULL,
  `longitude` VARCHAR(20) NOT NULL,
  `latitude` VARCHAR(20) NOT NULL,
  `timezone` TIME NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`airport_id`),
  INDEX `fk_airports_cities1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_airports_cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `AirplaneTickets`.`cities` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirplaneTickets`.`boarding_pases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`boarding_pases` (
  `boarding_pase_id` INT NOT NULL,
  `flight_id` INT NOT NULL,
  `ticket_id` INT NOT NULL,
  `fare_id` INT NOT NULL,
  `seat_id` INT NOT NULL,
  PRIMARY KEY (`boarding_pase_id`, `flight_id`, `ticket_id`, `fare_id`, `seat_id`),
  INDEX `fk_boarding_pases_tickets1_idx` (`ticket_id` ASC) VISIBLE,
  INDEX `fk_boarding_pases_fare_conditions1_idx` (`fare_id` ASC) VISIBLE,
  INDEX `fk_boarding_pases_seats1_idx` (`seat_id` ASC) VISIBLE,
  CONSTRAINT `fk_boarding_pases_flight_races1`
    FOREIGN KEY (`flight_id`)
    REFERENCES `AirplaneTickets`.`flights` (`flight_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boarding_pases_tickets1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `AirplaneTickets`.`tickets` (`ticket_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boarding_pases_fare_conditions1`
    FOREIGN KEY (`fare_id`)
    REFERENCES `AirplaneTickets`.`fare_statuses` (`fare_condition_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boarding_pases_seats1`
    FOREIGN KEY (`seat_id`)
    REFERENCES `AirplaneTickets`.`seats` (`seats_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirplaneTickets`.`booking_statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`booking_statuses` (
  `booking_status_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`booking_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirplaneTickets`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`bookings` (
  `book_id` INT NOT NULL,
  `book_date` DATETIME NOT NULL,
  `total_book` INT NOT NULL,
  `boocking_name` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  `booking_status_id` INT NOT NULL,
  PRIMARY KEY (`book_id`, `booking_status_id`),
  INDEX `fk_bookings_booking_status1_idx` (`booking_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_bookings_booking_status1`
    FOREIGN KEY (`booking_status_id`)
    REFERENCES `AirplaneTickets`.`booking_statuses` (`booking_status_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirplaneTickets`.`changing_flight_prices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`changing_flight_prices` (
  `changing_flight_prices_id` INT NOT NULL AUTO_INCREMENT,
  `previous_price` INT NOT NULL,
  `current_price` INT NOT NULL,
  `future_price` INT NOT NULL,
  PRIMARY KEY (`changing_flight_prices_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirplaneTickets`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`cities` (
  `city_id` INT NOT NULL,
  `city_name` VARCHAR(45) NOT NULL,
  `airports_amount` INT NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`city_id`),
  INDEX `country_id_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `country_id`
    FOREIGN KEY (`country_id`)
    REFERENCES `AirplaneTickets`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirplaneTickets`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`countries` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirplaneTickets`.`description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`description` (
  `description_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `scheduled_flight_id` INT NOT NULL,
  PRIMARY KEY (`description_id`, `scheduled_flight_id`),
  INDEX `fk_description_scheduled_flights1_idx` (`scheduled_flight_id` ASC) VISIBLE,
  CONSTRAINT `fk_description_scheduled_flights1`
    FOREIGN KEY (`scheduled_flight_id`)
    REFERENCES `AirplaneTickets`.`scheduled_flights` (`scheduled_flights_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirplaneTickets`.`fare_statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`fare_statuses` (
  `fare_condition_id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fare_condition_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirplaneTickets`.`flight_statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`flight_statuses` (
  `flight_status_id` INT NOT NULL,
  `status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`flight_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirplaneTickets`.`flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`flights` (
  `flight_id` INT NOT NULL,
  `sheduled_depature` DATETIME NOT NULL,
  `sheduled_arrival` DATETIME NOT NULL,
  `aircraft_code` INT NOT NULL,
  `actual_depature` DATETIME NOT NULL,
  `actual_arrival` DATETIME NOT NULL,
  `standart_price` INT NOT NULL,
  `arrival_airport_id` INT NOT NULL,
  `departure_airport_id` INT NOT NULL,
  `airplane_id` INT NOT NULL,
  `flight_status_id` INT NOT NULL,
  `scheduled_flight_id` INT NOT NULL,
  `changing_flight_prices_id` INT NOT NULL,
  PRIMARY KEY (`flight_id`, `airplane_id`, `flight_status_id`, `scheduled_flight_id`),
  INDEX `fk_flight_races_airports1_idx` (`arrival_airport_id` ASC) VISIBLE,
  INDEX `fk_flight_races_airports2_idx` (`departure_airport_id` ASC) VISIBLE,
  INDEX `fk_flight_races_airplanes1_idx` (`airplane_id` ASC) VISIBLE,
  INDEX `fk_flight_races_flight_statuses1_idx` (`flight_status_id` ASC) VISIBLE,
  INDEX `fk_flights_scheduled_flights1_idx` (`scheduled_flight_id` ASC) VISIBLE,
  UNIQUE INDEX `flight_id_UNIQUE` (`flight_id` ASC) VISIBLE,
  INDEX `fk_flights_changing_flight_prices1_idx` (`changing_flight_prices_id` ASC) VISIBLE,
  CONSTRAINT `fk_flight_races_airports1`
    FOREIGN KEY (`arrival_airport_id`)
    REFERENCES `AirplaneTickets`.`airports` (`airport_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flight_races_airports2`
    FOREIGN KEY (`departure_airport_id`)
    REFERENCES `AirplaneTickets`.`airports` (`airport_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flight_races_airplanes1`
    FOREIGN KEY (`airplane_id`)
    REFERENCES `AirplaneTickets`.`airplanes` (`airplane_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flight_races_flight_statuses1`
    FOREIGN KEY (`flight_status_id`)
    REFERENCES `AirplaneTickets`.`flight_statuses` (`flight_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flights_scheduled_flights1`
    FOREIGN KEY (`scheduled_flight_id`)
    REFERENCES `AirplaneTickets`.`scheduled_flights` (`scheduled_flights_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flights_changing_flight_prices1`
    FOREIGN KEY (`changing_flight_prices_id`)
    REFERENCES `AirplaneTickets`.`changing_flight_prices` (`changing_flight_prices_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirplaneTickets`.`passengers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`passengers` (
  `passenger_id` INT NOT NULL,
  `passenger_name` VARCHAR(45) NOT NULL,
  `passenger_surname` VARCHAR(45) NOT NULL,
  `contact_data` VARCHAR(45) NOT NULL,
  `passport_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`passenger_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirplaneTickets`.`scheduled_flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`scheduled_flights` (
  `scheduled_flights_id` INT NOT NULL AUTO_INCREMENT,
  `regularity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`scheduled_flights_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirplaneTickets`.`seat_classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`seat_classes` (
  `seat_class_id` INT NOT NULL AUTO_INCREMENT,
  `economy` VARCHAR(45) NULL,
  `business` VARCHAR(45) NULL,
  `first` VARCHAR(45) NULL,
  `economy_class_coefficient` DOUBLE NOT NULL,
  `business_class_coefficient` DOUBLE NOT NULL,
  `first_class_coefficient` DOUBLE NOT NULL,
  PRIMARY KEY (`seat_class_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirplaneTickets`.`seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`seats` (
  `seats_id` INT NOT NULL AUTO_INCREMENT,
  `seats_column` CHAR(1) NOT NULL,
  `seats_row` INT NOT NULL,
  `airplane_id` INT NOT NULL,
  PRIMARY KEY (`seats_id`),
  INDEX `airplane_id_idx` (`airplane_id` ASC) VISIBLE,
  CONSTRAINT `airplane_id`
    FOREIGN KEY (`airplane_id`)
    REFERENCES `AirplaneTickets`.`airplanes` (`airplane_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirplaneTickets`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirplaneTickets`.`ticket_statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`ticket_statuses` (
  `ticket_status_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ticket_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirplaneTickets`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AirplaneTickets`.`tickets` (
  `ticket_id` INT NOT NULL,
  `price` INT NOT NULL,
  `passenger_id` INT NOT NULL,
  `booking_id` INT NOT NULL,
  `ticket_status_id` INT NOT NULL,
  `seats_id` INT NOT NULL,
  PRIMARY KEY (`ticket_id`, `passenger_id`, `booking_id`, `ticket_status_id`),
  INDEX `fk_tickets_booking_idx` (`booking_id` ASC) VISIBLE,
  INDEX `fk_tickets_passengers1_idx` (`passenger_id` ASC) VISIBLE,
  INDEX `fk_tickets_ticket_status1_idx` (`ticket_status_id` ASC) VISIBLE,
  INDEX `fk_tickets_seats1_idx` (`seats_id` ASC) VISIBLE,
  CONSTRAINT `fk_tickets_booking`
    FOREIGN KEY (`booking_id`)
    REFERENCES `AirplaneTickets`.`bookings` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_passengers1`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `AirplaneTickets`.`passengers` (`passenger_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_ticket_status1`
    FOREIGN KEY (`ticket_status_id`)
    REFERENCES `AirplaneTickets`.`ticket_statuses` (`ticket_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_seats1`
    FOREIGN KEY (`seats_id`)
    REFERENCES `AirplaneTickets`.`seats` (`seats_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
